toolbar:
  - styleselect | bold italic | undo redo
  - image media | link | charmap wordcount | numlist bullist | codesample code | fullscreen preview nonbreaking
plugins:
  - image
  - link
  - charmap
  - lists
  - advlist
  - codesample
  - fullscreen
  - media
  - preview
  - nonbreaking
  - code
  - wordcount
nonbreaking_force_tab : true