toolbar:
  - styleselect | bold italic | undo redo
  - image media | link | charmap | numlist bullist | codesample | fullscreen preview
plugins:
  - image
  - link
  - charmap
  - lists
  - advlist
  - codesample
  - fullscreen
  - media
  - preview